name: at_keymaker
description: A new Flutter project
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.1.17
  at_utils: ^3.0.10
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.0
  at_backupkey_flutter: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  biometric_storage: ^4.1.3
  at_onboarding_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_onboarding_flutter
      ref: fix_flutter_qr_reader
  at_backupkey_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_backupkey_flutter
      ref: fix_flutter_qr_reader

flutter:
  uses-material-design: true
  assets:
    - .env

